### ISSUE TITLE
参考文献大小写问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [NEUAI/neuthesis-enhanced#1]
同学您好，东大的参考文献应该是首字母大写，其他字母小写，请问这个问题如何解决呢？

**Comment by NEUAI** [comment]
如果要保留bib文件中原始的大小写形式的话，可以对内容添加一组英文大括号，就会保留bib代码中原始的大小写形式。比如：
@book{lamport1986document,
    title={Document Preparation System},
    author={{Lamport}, {Leslie}}, % 这一行的作者在参考文献中出现时会保留首字母大写其他字母小写
    year={1986},
    publisher={Addison-Wesley Reading, MA}
}
希望的解决你的问题！

**Comment by JACKYLUO1991** [comment]
谢谢您 不过我最后直接从bst文件修改了



---原始邮件---
发件人: "Zhengpeng ***@***.***&gt;
发送时间: 2021年5月10日(周一) 晚上8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NEUAI/neuthesis-enhanced] 参考文献大小写问题 (#1)




 
如果要保留bib文件中原始的大小写形式的话，可以对内容添加一组英文大括号，就会保留bib代码中原始的大小写形式。比如：
 @book{lamport1986document,
 title={Document Preparation System},
 author={{Lamport}, {Leslie}}, % 这一行的作者在参考文献中出现时会保留首字母大写其他字母小写
 year={1986},
 publisher={Addison-Wesley Reading, MA}
 }
 希望的解决你的问题！

**Comment by NEUAI** [comment]
Okay!
